const ar = {
  nav: { dashboard:'لوحة القيادة', crm:'إدارة العملاء', projects:'المشاريع', tasks:'المهام', team:'الفريق', finance:'المالية', templates:'القوالب', settings:'الإعدادات' },
  auth: { login:'تسجيل الدخول', logout:'تسجيل الخروج', register:'إنشاء حساب', email:'البريد الإلكتروني', password:'كلمة المرور', name:'الاسم', phone:'الهاتف', loginTitle:'تسجيل الدخول', registerTitle:'إنشاء حساب عميل', noAccount:'ليس لديك حساب؟', haveAccount:'لديك حساب بالفعل؟', tryDemo:'تجربة الديمو' },
  common: { add:'إضافة', edit:'تعديل', delete:'حذف', save:'حفظ', cancel:'إلغاء', confirm:'تأكيد', search:'بحث...', filter:'تصفية', export:'تصدير', actions:'إجراءات', status:'الحالة', date:'التاريخ', notes:'الملاحظات', loading:'جاري التحميل...', noData:'لا توجد بيانات', yes:'نعم', no:'لا', close:'إغلاق', submit:'إرسال', saveDraft:'حفظ مسودة', print:'طباعة', view:'عرض', details:'التفاصيل', all:'الكل', amount:'المبلغ', currency:'العملة', name:'الاسم', email:'البريد', phone:'الهاتف', company:'الشركة', description:'الوصف', type:'النوع', priority:'الأولوية', assignee:'المسؤول', project:'المشروع', customer:'العميل', createdAt:'تاريخ الإنشاء', dueDate:'تاريخ الاستحقاق', startDate:'تاريخ البداية', endDate:'تاريخ النهاية', required:'مطلوب', optional:'اختياري', areYouSure:'هل أنت متأكد؟', deleteConfirm:'سيتم حذف هذا العنصر نهائيًا.', success:'تم بنجاح', error:'حدث خطأ' },
  status: { draft:'مسودة', active:'نشط', inactive:'غير نشط', suspended:'معلق', lost:'خسارة', prospect:'محتمل', qualified:'مؤهل', negotiation:'تفاوض', completed:'مكتمل', cancelled:'ملغى', on_hold:'متوقف', new:'جديد', assigned:'مسند', in_progress:'قيد التنفيذ', ready_for_handover:'جاهز للتسليم', handed_over:'تم التسليم', under_review:'قيد المراجعة', reopened:'أعيد فتحه', paid:'مدفوعة', unpaid:'غير مدفوعة', partially_paid:'مدفوعة جزئيًا', overdue:'متأخرة', issued:'صادرة', not_started:'لم يبدأ', submitted:'مُرسل', reviewing:'قيد المراجعة', changes_requested:'يتطلب تعديلات', approved:'معتمد', unassigned:'غير مسند', partial:'جزئي', ready:'جاهز', available:'متاح', busy:'مشغول', unavailable:'غير متاح', low:'منخفض', medium:'متوسط', high:'عالي', urgent:'عاجل', subscription:'اشتراك', onetime:'مرة واحدة' },
  dashboard: { title:'لوحة القيادة', activeCustomers:'عملاء نشطون', activeProjects:'مشاريع نشطة', openTasks:'مهام مفتوحة', overdueTasks:'مهام متأخرة', collected:'المحصّل', expenses:'المصروفات', net:'الصافي', unpaidInvoices:'فواتير غير مدفوعة', period:'الفترة', today:'اليوم', last7:'آخر 7 أيام', last30:'آخر 30 يوم', thisMonth:'الشهر الحالي', thisQuarter:'الربع الحالي', custom:'مخصص', revenue:'الإيرادات', profit:'صافي الربح', customers:'العملاء', pendingTasks:'مهام معلقة', recentActivity:'النشاط الأخير', quickActions:'إجراءات سريعة', newInvoice:'فاتورة جديدة', addCustomer:'إضافة عميل', newProject:'مشروع جديد', logExpense:'تسجيل مصروف', revenueVsExpenses:'الإيرادات مقابل المصروفات', monthlyOverview:'نظرة شهرية', greetingMorning:'صباح الخير', greetingAfternoon:'مساء الخير', greetingEvening:'مساء الخير', greetingSubtitle:'إليك ما يحدث الآن', marginLabel:'هامش' },
  crm: { title:'إدارة العملاء', addCustomer:'إضافة عميل', pipeline:'Pipeline', list:'القائمة', source:'المصدر', budget:'الميزانية', nextAction:'الإجراء التالي', followUpDate:'موعد المتابعة', lostReason:'سبب الخسارة', tags:'Tags', assignedTo:'المسؤول', score:'النقاط', bulkAction:'إجراء جماعي', updateStatus:'تحديث الحالة', archive:'أرشفة', exportCSV:'تصدير CSV', duplicateFound:'يوجد تكرار محتمل', forceCreate:'إنشاء على أي حال', priority:'الأولوية', allStatuses:'كل الحالات', editCustomer:'تعديل العميل', deleteCustomer:'حذف العميل', noCustomers:'لا يوجد عملاء', clients:'العملاء', addClient:'إضافة عميل', clientsSubtitle:'إدارة عملاؤك وقمع المبيعات', totalClients:'إجمالي العملاء', active:'نشط', leads:'عملاء محتملون', highPriority:'أولوية عالية', searchClients:'بحث عن عملاء…', editClient:'تعديل العميل', addNewClient:'إضافة عميل جديد', noClients:'لا يوجد عملاء', addFirstClient:'أضف أول عميل للبدء', deleteClient:'حذف العميل', deleteClientMsg:'قد تتأثر جميع البيانات المرتبطة.', fullName:'الاسم الكامل', searchCustomers:'بحث عن عملاء…' },
  projects: { title:'المشاريع', addProject:'إضافة مشروع', workflowMode:'طريقة العمل', manual:'يدوي', sequential:'متسلسل', template:'القالب', briefTemplate:'قالب البريف', accountManager:'مسؤول الحساب', estimatedCost:'التكلفة التقديرية', taxRate:'نسبة الضريبة', billable:'قابل للفاتورة', targetDate:'التاريخ المستهدف', copyBriefLink:'نسخ رابط البريف', openBrief:'فتح البريف', assignmentStatus:'حالة الإسناد', allStatuses:'كل الحالات', editProject:'تعديل المشروع', deleteProject:'حذف المشروع', noProjects:'لا توجد مشاريع', selectCustomer:'اختر عميلاً', due:'الاستحقاق:', brief:'البريف' },
  brief: { title:'بريف المشروع', questions:'الأسئلة', comments:'التعليقات', addComment:'إضافة تعليق', status:'حالة البريف', submitBrief:'إرسال البريف' },
  tasks: { title:'المهام', addTask:'إضافة مهمة', taskType:'نوع المهمة', currentAssignee:'المسؤول الحالي', reviewRequired:'يتطلب مراجعة', handover:'تسليم', handoverTo:'تسليم إلى', handoverNote:'ملاحظة التسليم', start:'بدء', complete:'اكتمال', reopen:'إعادة فتح', sendToReview:'إرسال للمراجعة', cancel:'إلغاء', efficiencyScore:'نقاط الكفاءة', handoverHistory:'سجل التسليم', teamDue:'مستحق الفريق', paymentStatus:'حالة الدفع', allStatuses:'كل الحالات', taskTitle:'العنوان', taskProject:'المشروع', taskAssignee:'المسؤول', taskPriority:'الأولوية', taskStatus:'الحالة', taskDue:'الاستحقاق', taskActions:'إجراءات', noTasks:'لا توجد مهام', editTask:'تعديل المهمة', handoverTask:'تسليم المهمة', deleteTask:'حذف المهمة', noProject:'بدون مشروع', unassigned:'غير مسند', assignTo:'إسناد إلى:', selectEmployee:'اختر موظفاً' },
  team: { title:'الفريق', addEmployee:'إضافة عضو', internalRole:'الدور الداخلي', accountManager:'مسؤول حساب', taskMember:'عضو تنفيذ', skills:'المهارات', specializations:'التخصصات', availability:'التوفر', onLeave:'في إجازة', linkedAccount:'الحساب المرتبط', createAccount:'إنشاء حساب', editEmployee:'تعديل الموظف', removeEmployee:'إزالة الموظف', removeEmployeeMsg:'من الفريق؟', noTeamMembers:'لا يوجد أعضاء في الفريق', tasks:'المهام', overdue:'متأخر', monthly:'شهرياً', role:'الدور', selectRole:'اختر الدور', salary:'الراتب', hrTitle:'الموارد البشرية والرواتب', hrSubtitle:'إدارة الموظفين وصرف الرواتب', totalEmployees:'إجمالي الموظفين', monthlyBudget:'الميزانية الشهرية', paidThisMonth:'مدفوع هذا الشهر', payrollRecords:'سجلات الرواتب', employees:'الموظفون', payrollHistory:'سجل الرواتب', paySalary:'صرف الراتب', perMonth:'/ شهر', noEmployees:'لا يوجد موظفون بعد', addFirstEmployee:'أضف أول موظف لإدارة الرواتب', noPayroll:'لا توجد سجلات رواتب بعد', fullName:'الاسم الكامل', rolePosition:'الدور / المسمى الوظيفي', selectRoleDots:'اختر الدور…', monthlySalary:'الراتب الشهري', disburse:'صرف الراتب', processing:'جاري المعالجة…', removeEmpMsg:'من الفريق؟ لا يمكن التراجع عن هذا.' },
  finance: { title:'المالية', invoices:'الفواتير', expenses:'المصروفات', salaryTemplates:'الرواتب الثابتة', addInvoice:'إضافة فاتورة', addExpense:'إضافة مصروف', addSalary:'إضافة راتب', invoiceNumber:'رقم الفاتورة', subtotal:'المجموع قبل الضريبة', tax:'الضريبة', total:'الإجمالي', paidAmount:'المدفوع', remaining:'المتبقي', issueDate:'تاريخ الإصدار', category:'التصنيف', expenseType:'نوع المصروف', single:'منفرد', distributed:'موزع', salary:'راتب', distributionMode:'طريقة التوزيع', selectedCustomers:'عملاء محددون', activeCustomers:'كل العملاء النشطين', salaryEmployee:'الموظف', salaryAmount:'قيمة الراتب', salaryStart:'بداية الراتب', viewPDF:'عرض PDF', collection:'التحصيل', netProfit:'الصافي' },
  templates: { title:'القوالب', addTemplate:'إضافة قالب', kind:'النوع', addQuestion:'إضافة سؤال', addStage:'إضافة مرحلة', specialtyWeight:'وزن التخصص', industryWeight:'وزن القطاع', availabilityWeight:'وزن التوفر', workloadWeight:'وزن الحمل', recommend:'اقتراح إسناد' },
  settings: { title:'الإعدادات', general:'عام', language:'اللغة', currency:'العملات', permissions:'الصلاحيات', audit:'سجل المراجعة', companyName:'اسم الشركة', companyLogo:'شعار الشركة', companyDesc:'وصف الشركة', theme:'المظهر', light:'فاتح', dark:'داكن', primaryColor:'اللون الأساسي', defaultLanguage:'اللغة الافتراضية', baseCurrency:'العملة الأساسية', exchangeRates:'أسعار الصرف', roles:'الأدوار', rolePermissions:'صلاحيات الأدوار', userOverrides:'تخصيص صلاحيات', auditTrail:'سجل التغييرات' },
  portal: { title:'بوابة العملاء', projects:'مشاريعي', invoices:'فواتيري', totalProjects:'إجمالي المشاريع', totalInvoices:'إجمالي الفواتير', unpaidTotal:'مبلغ غير مدفوع', recentProjects:'أحدث المشاريع', recentInvoices:'أحدث الفواتير', openBrief:'استكمال البريف' },
} as const

export default ar
export type Translations = typeof ar
